name: Build and deploy

on:
  workflow_dispatch:
  push:

concurrency:
  group: cd-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: version-tag
        uses: ./.github/actions/get-version-tag
      - name: Build Docker image
        uses: ./.github/actions/docker-build
        with:
          version: ${{ steps.version-tag.outputs.version-tag }}
          latest: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}

  build2:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Create version tag
        id: version-tag
        uses: nationalarchives/ds-docker-actions/.github/actions/get-version-tag
      - name: Build Docker image
        uses: nationalarchives/ds-docker-actions/.github/actions/docker-build
        with:
          version: ${{ steps.version-tag.outputs.version-tag }}
          latest: ${{ github.ref == 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}